name: tekartik_mdc_js
description: An absolute bare-bones web app.
version: 0.3.1
#homepage: https://www.example.com
#author: alex <email@example.com>

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  tekartik_browser_utils:
    git:
      url: git://github.com/tekartik/browser_utils.dart
      ref: dart2
dev_dependencies:
  tekartik_mdc_asset:
    git:
      url: git://github.com/tekartik/mdc_asset.dart
      ref: dart2
    version: '>=0.42.1'
  test: any
  dev_test: any
  chrome_travis:
    git:
      url: git://github.com/tekartik/chrome_travis.dart
      ref: dart2
  tekartik_material_asset:
    git:
      url: git://github.com/tekartik/material_asset.dart
      ref: dart2
  tekartik_app_utils:
    git:
      url: git://github.com/tekartik/app_utils.dart
      ref: dart2
  build_runner: '>=0.9.1'
  build_test: '>=0.10.2'
  build_web_compilers: '>=0.4.0'
  tekartik_common_utils:
    git:
      url: git://github.com/tekartik/common_utils.dart
      ref: dart2
  process_run: